# Config file for automatic testing at travis-ci.org

language: python

services:
  - postgresql

matrix:
  include:
  - python: "3.5"
    env: TOX_ENV=py35-django-20
  - python: "3.6"
    env: TOX_ENV=py36-django-20

before_script:
  - psql -c 'create database django_approval;' -U postgres

install: pip install pipenv && pipenv install --dev

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
